#!/usr/bin/env bash

# PocketMine server port
mc_port=19132
port=${1:-${PORT:-8080}}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

# Set the auth token into the config file, V2 of ngrok
bin/ngrok authtoken $NGROK_API_TOKEN
echo "log: ngrok.log" >> $HOME/.ngrok2/ngrok.yml
echo "log_level: debug" >> $HOME/.ngrok2/ngrok.yml
# Start the TCP tunnel
ngrok_cmd="bin/ngrok ${NGROK_OPTS} udp ${mc_port}"
echo "Starting ngrok..."
eval "$ngrok_cmd &"
ngrok_pid=$!

# Do an inline sync first, then start the background job
echo "Starting sync..."
bin/sync
eval "while true; do sleep ${AWS_SYNC_INTERVAL:-60}; bin/sync; done &"
sync_pid=$!

echo "Starting: minecraft-PE ${mc_port}"
eval "./start.sh &"
main_pid=$!

trap "kill $ngrok_pid $main_pid $sync_pid" SIGTERM
trap "kill -9 $ngrok_pid $main_pid $sync_pid; exit" SIGKILL

eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${port}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"
