#!/usr/bin/env bash

# PocketMine server port
mc_port=19132
port=${1:-${PORT:-8080}}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

# Set the auth token into the config file, V2 of ngrok
bin/ngrok authtoken $NGROK_API_TOKEN
echo "log: ngrok.log" >> $HOME/.ngrok2/ngrok.yml
echo "log_level: debug" >> $HOME/.ngrok2/ngrok.yml
# Start the TCP tunnel
ngrok_cmd="bin/ngrok ${NGROK_OPTS} tcp ${mc_port}"
echo "Starting ngrok..."
eval "$ngrok_cmd &"
ngrok_pid=$!

# Do an inline sync first, then start the background job
echo "Starting sync..."
bin/sync
eval "while true; do sleep ${AWS_SYNC_INTERVAL:-60}; bin/sync; done &"
sync_pid=$!

# create server config
# Server.properties - change as you require... 
cat > server.properties << EOF
#Properties Config file
#Sun May 31 22:32:00 BST 2015
server-name=minecraft
server-port=19132
memory-limit=256M
gamemode=0
max-players=20
spawn-protection=16
white-list=off
enable-query=on
enable-rcon=off
motd=Minecraft: PE Server
announce-player-achievements=on
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
rcon.password=i6r8sp/F/s
auto-save=on
EOF

# TODO: Change to a defined id
echo "server-admin" > ops.txt


echo "Starting: minecraft-PE ${mc_port}"
eval "./start.sh &"
main_pid=$!

trap "kill $ngrok_pid $main_pid $sync_pid" SIGTERM
trap "kill -9 $ngrok_pid $main_pid $sync_pid; exit" SIGKILL

eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${port}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"
